<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class export extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        //$this->load->model('Battery_model');
        //$this->load->library('pdf');
        $this->load->model('battery_model');
        $this->load->model('battery_pesaing_model');
        $this->load->model('diesel_model');
        $this->load->model('diesel_pesaing_model');
    }

    public function cetak($produk,$pilihan){
        $pdfFilePath = FCPATH."/downloads/hasil.pdf";

        //$data['page_title'] = "Hello World";
        //$data['header'] = $this->load->view('inti/header','',true);
        //$data['body'] = $this->load->view('frontend/battery_compare','',true);
        //$data['footer'] = $this->load->view('inti/footer','',true);

        if (file_exists($pdfFilePath) == FALSE)

        {
             $data['forklift']=$this->battery_model->get_by_id($produk);
            $data['pesaing']=$this->battery_pesaing_model->get_by_id($pilihan);

            ini_set('memory_limit','32M'); 
            //baris ini kan mangview battery_compare, nah di battery_compare itu ada yang dipanggil dari parameterfungsi di controllernya
            $html = $this->load->view('frontend/battery_compare', $data, true); 

            $this->load->library('pdf');

            $pdf = $this->pdf->load();

            $pdf->SetFooter($_SERVER['HTTP_HOST'].'|{PAGENO}|'.date(DATE_RFC822)); 

            $pdf->WriteHTML($html); 

            $pdf->Output($pdfFilePath, 'D'); 

        }


        redirect("/downloads/hasil.pdf");
            // $pdfFilePath = FCPATH."/downloads/test.pdf";
            // ini_set('memory_limit','32M'); 

            // $html = $this->load->view('frontend/battery_compare','',true);
            // $this->load->library('pdf');
            // $pdf = $this->pdf->load();
            // $pdf->WriteHTML($html);
            // $pdf->Output($pdfFilePath, 'D'); 
        // $this->load->library('Pdf');
        //   $this->pdf->load_view('frontend/battery_compare');
        //   $this->pdf->render();
        //   $this->pdf->stream("welcome.pdf");
       }

        public function cetakdiesel($produk,$pilihan){
        $pdfFilePath = FCPATH."/downloads/hasil.pdf";

        //$data['page_title'] = "Hello World";
        //$data['header'] = $this->load->view('inti/header','',true);
        //$data['body'] = $this->load->view('frontend/battery_compare','',true);
        //$data['footer'] = $this->load->view('inti/footer','',true);

        if (file_exists($pdfFilePath) == FALSE)

        {
             $data['forklift']=$this->diesel_model->get_by_id($produk);
            $data['pesaing']=$this->diesel_pesaing_model->get_by_id($pilihan);

            ini_set('memory_limit','32M'); 
            //baris ini kan mangview battery_compare, nah di battery_compare itu ada yang dipanggil dari parameterfungsi di controllernya
            $html = $this->load->view('frontend/diesel_compare', $data, true); 

            $this->load->library('pdf');

            $pdf = $this->pdf->load();

            $pdf->SetFooter($_SERVER['HTTP_HOST'].'|{PAGENO}|'.date(DATE_RFC822)); 

            $pdf->WriteHTML($html); 

            $pdf->Output($pdfFilePath, 'D'); 

        }


        redirect("/downloads/hasil.pdf");
            // $pdfFilePath = FCPATH."/downloads/test.pdf";
            // ini_set('memory_limit','32M'); 

            // $html = $this->load->view('frontend/battery_compare','',true);
            // $this->load->library('pdf');
            // $pdf = $this->pdf->load();
            // $pdf->WriteHTML($html);
            // $pdf->Output($pdfFilePath, 'D'); 
        // $this->load->library('Pdf');
        //   $this->pdf->load_view('frontend/battery_compare');
        //   $this->pdf->render();
        //   $this->pdf->stream("welcome.pdf");
       }
   

}

/* End of file Buku.php */
/* Location: ./application/controllers/Buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */